[package]
name = "paul"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
ed25519-dalek = "2.1.1"
hex = "0.4.3"
rand = "0.8.5"
reqwest = { version = "0.12.12", features = ["multipart"] }
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["full"] }
